spring:
  application:
    name: jooq
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8023
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG